# Generated by Django 5.0.4 on 2024-04-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('interface_name', models.CharField(max_length=256)),
                ('interface', models.CharField(max_length=2560)),
                ('info', models.CharField(max_length=2560)),
            ],
        ),
    ]
